import { Header } from "@/components/header/Header";
import { Inter } from "next/font/google";
import "../styles/global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    //inter.className serve para aplicar a fonte
    <div className={inter.className}>
      <Header />
      <div>{children}</div>
    </div>
  );
}
